### ISSUE TITLE
HOL Feedback on Lab101 "Hello NServiceBus World": Links for more info on interfaces

### ISSUE THREAD

**Issue by SimonCropp** [Particular/HandsOnLabs#1]
Raised by @dannycohen
Migrated from by https://github.com/Particular/docs.particular.net/issues/136

> I think there needs to be some hyper links that explain in a little more about  the interfaces that are used and why

**Comment by SimonCropp** [comment]
@dannycohen @indualagarsamy is this still an issue?

**Comment by indualagarsamy** [comment]
@SimonCropp - I don't think we have plans at the moment to change the manuals. Last update i did was just to convert them to v5 guidelines. Closing this issue.
